import fs from "fs";
import path from "path";

/**
 * inits .grida directory if it does not exist.
 */
export function init_dotgrida(cwd = process.cwd()): {
  dir_created: boolean;
} {
  const dotgrida_path = path.join(cwd, ".grida");
  const exists = fs.existsSync(dotgrida_path);
  if (!exists) {
    fs.mkdirSync(dotgrida_path);
    // this does not impact any logic, so this is not handled in ".grida directory already exists" case.
    fs.writeFileSync(path.join(dotgrida_path, "README.md"), README_CONTENT);
  }

  return {
    dir_created: !exists,
  };
}

const README_CONTENT = `# \`.grida\`

This directory is auto generated by \`grida init\` and contains configuration and cache files.
Please do not manually edit files under this directory unless intended to do so.

**If you want, you can always remove this directory.** (Though it will be re-generated by grida cli.)
- Removing this directory will remove all configuration and cache files, which is recommended to do regullarly to prevent local cache bugs.
- Removing this directory executing the grida command will fail the process.

The \`.grida\` directory is automatically added to \`.gitignore\` file, but somehow if it is included to version control, you may want to modify your git configuration to exclude it.

Learn more about .grida & grida cli at https://grida.co/cli
`;
