import fs from "fs";
import path from "path";
import type { GridaConfig } from "../config";
import JSON5 from "json5";

export function create_grida_config_js(
  cwd = process.cwd(),
  config: GridaConfig
) {
  const grida_config_js = path.join(cwd, "grida.config.js");
  if (fs.existsSync(grida_config_js)) {
    throw new Error(`grida.config.js already exists in ${cwd}`);
  }
  const configjson = JSON5.stringify(config, null, 2);
  const src = `// This file is auto-generated by Grida.

/**
 * @type {import('grida').GridaConfig}
 */
const config = ${configjson};

module.exports = config;`;
  fs.writeFileSync(grida_config_js, src);
}
