// THIS IS NOT A SPEC TEST FILE.
// USED FOR TSDOC PREVIEW INSIDE VSCODE.
// THE BELOW CONTENT SHALL MATCH THE TEMPLATE ON README.MD

/**
 * ${Widget} from design - {@link https://grida.co/files/xxx/yyy}
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function (){
 *    return (
 *      <>
 *        👇 instanciate widget like below. 👇
 *        <Widget/>
 *      </>
 *    );
 * }
 * ```
 * ---
 * @param props (any) - this widget does not contains any typed props, but you can pass dynamic props as you want.
 *
 * ---
 * @preview
 * ![widget render preview](https://bridged-service-static.s3.us-west-1.amazonaws.com/device-frames/iphone-11-fit-black-no-shadow.png)
 *
 * [view on browser](https://grida.co)
 *
 * ---
 * @remarks
 * @see {@link https://grida.co/docs/widgets} for more information.
 *
 * ---
 * @privateRemarks
 * Code generated by grida.co | engine v2022.1.0 (Apache-2.0) | Generated code under CC0 (public domain)
 * *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 *
 * ![](https://bridged-service-static.s3.us-west-1.amazonaws.com/opengraph/og-image-gif.gif)
 *
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta | engine: v2022.1.0 | source: ${id} | uri: ${resource-uri} -->
 */
function Widget() {
  // ...
}
