// This file is auto-generated by Grida.

/**
 * @type {import('grida').GridaConfig}
 */
const config = {
  name: 'my-react-app',
  designsource: {
    provider: 'figma',
    file: 'x7RRK6RwWtZuNakmbMLTVH',
    client: 'api.figma.com',
  },
  fallbackDir: './grida',
  framework: {
    framework: 'react',
    language: 'tsx',
    styling: {
      type: 'styled-components',
      module: '@emotion/styled',
    },
    component_declaration_style: {
      exporting_style: {
        type: 'export-named-functional-component',
        declaration_syntax_choice: 'function',
        export_declaration_syntax_choice: 'export',
        exporting_position: 'with-declaration',
      },
    },
  },
};

module.exports = config;