import type {
  EsComponentExportingConfig_ExportDefaultAnonymousClassComponent,
  EsComponentExportingConfig_ExportDefaultAnonymousFunctionalComponent,
  EsComponentExportingConfig_ExportNamedClassComponent,
  EsComponentExportingConfig_ExportNamedFunction,
} from "../module-es";

export type ReactComponentExportingCofnig =
  | ReactComponentExportingConfig_ExportDefaultAnonymousFunctionalComponent
  | ReactComponentExportingConfig_ExportNamedFunction
  | ReactComponentExportingConfig_ExportDefaultAnonymousClassComponent
  | ReactComponentExportingConfig_ExportNamedClassComponent;

type ReactComponentExportingConfig_ExportDefaultAnonymousFunctionalComponent =
  EsComponentExportingConfig_ExportDefaultAnonymousFunctionalComponent;
type ReactComponentExportingConfig_ExportNamedFunction =
  EsComponentExportingConfig_ExportNamedFunction;
type ReactComponentExportingConfig_ExportDefaultAnonymousClassComponent =
  EsComponentExportingConfig_ExportDefaultAnonymousClassComponent;
type ReactComponentExportingConfig_ExportNamedClassComponent =
  EsComponentExportingConfig_ExportNamedClassComponent;
